:PROPERTIES:
:ID:       is-graphic-pornography-cause-of-serial-killers
:START:    2025-01-08
:FINISH:
:CERTAINTY: possible
:STATUS:    rough
:IMPORTANCE: 6
:PREVIEW:   Investigating the correlation between extreme pornography and violent offenders
:END:
#+title: Is Graphic Pornography a Cause of Serial Killers?
#+filetags: :psychology:criminology:research-question:

* Question

Is graphic, extreme pornography a cause of serial killers, rapists, and other mortal offenders? Or at least have strong positive correlation?

* Premise (Why I'm asking)

I've noticed what appears to be a strongly repeating pattern of serial killers, and sexual offenders were on the record claiming use of "strong pornography". Including people like Ted Bundy, Jeffrey Dahmer, Richard Ramirez, Dennis Rader, Andrei Chikatilo, and more. I have also noticed that a increasing amount of activist, streamers, and general figures in the public sphere that seem to defend use of pornographic content through "moderation" seem to be into deeper more obscure sexual interests. Which is often a sign of unmoderated use of pornography destabilizing their own argument. Furthermore it has been exposed that among these people "Lolicon" a term established in japan for animated characters with child like features that are often in age ranges of 100-800 years old being vampires or other figures known to live a long time. They often make the claim that "CP" is not hurting anyone if it is not even real, and that even the real "CP" is not bad if the child agrees claims one offender Thaddeus McMichael aka "MadThad0890". It is to no surprise that some of these figures have come under charges for harboring sexually explicit content of minors.

* Prior Beliefs

/To be developed/

* What Would Resolve This?

/To be developed/
